# Generated by Django 3.1 on 2020-08-23 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cow',
            new_name='CowText',
        ),
    ]
